// Source of truth for keys. Keep HELP_SECTIONS in sync when adding a command.
export const DEFAULT_MAPPINGS = {
  j: "scrollDown",
  k: "scrollUp",
  h: "scrollLeft",
  l: "scrollRight",
  gg: "scrollToTop",
  G: "scrollToBottom",
  d: "scrollPageDown",
  u: "scrollPageUp",
  f: "hintCurrentTab",
  F: "hintNewTab",
  r: "reload",
  yy: "yankUrl",
  p: "openClipboard",
  P: "openClipboardNewTab",
  i: "enterInsert",
  gi: "focusFirstInput",
  J: "tabLeft",
  K: "tabRight",
  g0: "firstTab",
  "g$": "lastTab",
  t: "newTab",
  yt: "duplicateTab",
  x: "closeTab",
  X: "restoreTab",
  H: "goBack",
  L: "goForward",
  o: "paletteOpen",
  O: "paletteOpenNewTab",
  T: "paletteTabs",
  "?": "help",
};

export const HELP_SECTIONS = [
  {
    title: "Page",
    keys: [
      ["j k", "Scroll down / up"],
      ["h l", "Scroll left / right"],
      ["d u", "Half-page down / up"],
      ["gg G", "Top / bottom"],
      ["f F", "Follow link / in a new tab"],
      ["r", "Reload"],
      ["yy", "Copy URL"],
      ["p P", "Open clipboard URL / in a new tab"],
      ["i", "Insert mode"],
      ["gi", "Focus first input"],
      ["Esc", "Back to normal"],
    ],
  },
  {
    title: "Tabs",
    keys: [
      ["J K", "Tab left / right"],
      ["g0 g$", "First / last tab"],
      ["t yt", "New tab / duplicate"],
      ["x X", "Close / restore tab"],
      ["H L", "Back / forward"],
    ],
  },
  {
    title: "Palette",
    keys: [
      ["o O", "Open URL or tab / in a new tab"],
      ["T", "Search tabs"],
      ["?", "This cheatsheet"],
    ],
  },
];
