/* generated by npm run build — edit extension/src instead */

(() => {
  // extension/src/access.js
  var ALL_URLS = { origins: ["<all_urls>"] };
  async function handleToolbarClick(tab, api) {
    const { permissions, sendMessage, reload } = api;
    let hadAccess = false;
    try {
      hadAccess = await permissions.contains(ALL_URLS);
    } catch {
      hadAccess = false;
    }
    if (!hadAccess) {
      let granted = false;
      try {
        granted = await permissions.request(ALL_URLS);
      } catch {
        granted = false;
      }
      if (granted && tab?.id != null) {
        await reload(tab.id);
      }
      return { requested: true, granted };
    }
    if (tab?.id != null) {
      try {
        await sendMessage(tab.id, { type: "showHelp" });
      } catch {
      }
    }
    return { requested: false, granted: true };
  }

  // extension/src/browser.js
  var fallback = {
    runtime: {
      sendMessage: async () => ({}),
      onMessage: { addListener() {
      } }
    },
    storage: { onChanged: { addListener() {
    } } }
  };
  function extensionApi() {
    return globalThis.browser ?? globalThis.chrome ?? fallback;
  }

  // extension/src/settings.js
  var defaultSettings = {
    excludedHosts: [],
    hintCharacters: "sadfjklewcmpgh",
    scrollStep: 60,
    smoothScroll: true
  };
  function normalizeSettings(raw) {
    const input = raw && typeof raw === "object" ? raw : {};
    const hintCharacters = typeof input.hintCharacters === "string" && input.hintCharacters.length > 0 ? input.hintCharacters : defaultSettings.hintCharacters;
    const scrollStep = Number.isFinite(input.scrollStep) && input.scrollStep > 0 ? Math.floor(input.scrollStep) : defaultSettings.scrollStep;
    const smoothScroll = typeof input.smoothScroll === "boolean" ? input.smoothScroll : defaultSettings.smoothScroll;
    const excludedHosts = Array.isArray(input.excludedHosts) ? input.excludedHosts.map((host) => String(host).trim().toLowerCase()).filter(Boolean) : [];
    return { excludedHosts, hintCharacters, scrollStep, smoothScroll };
  }

  // extension/src/tabs.js
  function nextTabIndex(tabs, currentIndex, delta) {
    if (!tabs.length) {
      return 0;
    }
    const sorted = [...tabs].sort((a, b) => a.index - b.index);
    const len = sorted.length;
    return (currentIndex + delta + len * 50) % len;
  }
  function collectClosedTab(stack, tab) {
    if (!tab?.url) {
      return stack;
    }
    const next = [...stack, { url: tab.url, title: tab.title || tab.url }];
    return next.slice(-50);
  }
  function restoreClosedTab(stack) {
    if (!stack.length) {
      return { stack, tab: null };
    }
    const tab = stack[stack.length - 1];
    return { stack: stack.slice(0, -1), tab };
  }

  // extension/src/tab-commands.js
  function createTabState() {
    return { closedTabs: [], tabCache: /* @__PURE__ */ new Map() };
  }
  function cacheTab(state2, tab) {
    if (tab?.id != null) {
      state2.tabCache.set(tab.id, {
        url: tab.url,
        title: tab.title,
        id: tab.id,
        index: tab.index
      });
    }
  }
  function rememberClosedTab(state2, tabId) {
    const cached = state2.tabCache.get(tabId);
    if (cached) {
      state2.closedTabs = collectClosedTab(state2.closedTabs, cached);
      state2.tabCache.delete(tabId);
    }
  }
  async function refreshTabCache(browser2, state2) {
    const tabs = await browser2.tabs.query({});
    state2.tabCache.clear();
    for (const tab of tabs) {
      cacheTab(state2, tab);
    }
  }
  async function activeTab(browser2) {
    const tabs = await browser2.tabs.query({ active: true, currentWindow: true });
    return tabs[0];
  }
  async function windowTabs(browser2) {
    return browser2.tabs.query({ currentWindow: true });
  }
  async function activateTab(browser2, tab) {
    if (tab) {
      await browser2.tabs.update(tab.id, { active: true });
    }
  }
  async function navigateTo(browser2, tab, url, { newTab = false, background = false, createIfMissing = false } = {}) {
    if (!url) {
      return;
    }
    if (newTab) {
      await browser2.tabs.create({ url, ...background ? { active: false } : {} });
      return;
    }
    if (tab?.id != null) {
      await browser2.tabs.update(tab.id, { url });
      return;
    }
    if (createIfMissing) {
      await browser2.tabs.create({ url });
    }
  }
  async function repeat(count, fn) {
    for (let i = 0; i < count; i++) {
      await fn();
    }
  }
  async function handleCommand(message, sender, { browser: browser2, getSettings: getSettings2, state: state2 }) {
    const count = message.count ?? 1;
    const tab = sender.tab || await activeTab(browser2);
    switch (message.type) {
      case "getSettings":
        return getSettings2();
      case "listTabs":
        return windowTabs(browser2);
      case "tabLeft":
      case "tabRight": {
        const tabs = await windowTabs(browser2);
        const current = tabs.find((item) => item.id === tab?.id);
        if (!current) {
          return { ok: false };
        }
        const delta = (message.type === "tabLeft" ? -1 : 1) * count;
        const index = nextTabIndex(tabs, current.index, delta);
        await activateTab(browser2, tabs.find((item) => item.index === index) || tabs[index]);
        return { ok: true };
      }
      case "firstTab":
      case "lastTab": {
        const tabs = (await windowTabs(browser2)).sort((a, b) => a.index - b.index);
        await activateTab(browser2, message.type === "firstTab" ? tabs[0] : tabs[tabs.length - 1]);
        return { ok: true };
      }
      case "newTab":
        await repeat(count, () => browser2.tabs.create({}));
        return { ok: true };
      case "duplicateTab":
        if (tab?.id != null) {
          await repeat(count, () => browser2.tabs.duplicate(tab.id));
        }
        return { ok: true };
      case "closeTab":
        if (tab?.id != null) {
          await browser2.tabs.remove(tab.id);
        }
        return { ok: true };
      case "restoreTab": {
        const restored = restoreClosedTab(state2.closedTabs);
        state2.closedTabs = restored.stack;
        if (restored.tab?.url) {
          await browser2.tabs.create({ url: restored.tab.url });
        }
        return { ok: Boolean(restored.tab) };
      }
      case "goBack":
        if (tab?.id != null) {
          await browser2.tabs.goBack(tab.id);
        }
        return { ok: true };
      case "goForward":
        if (tab?.id != null) {
          await browser2.tabs.goForward(tab.id);
        }
        return { ok: true };
      case "openUrl":
        await navigateTo(browser2, tab, message.url, { newTab: message.newTab, background: true });
        return { ok: true };
      case "activatePaletteItem": {
        const item = message.item;
        if (!item) {
          return { ok: false };
        }
        if (item.kind === "tab" && item.tabId != null) {
          await activateTab(browser2, { id: item.tabId });
          return { ok: true };
        }
        await navigateTo(browser2, tab, item.url, { newTab: message.newTab, createIfMissing: true });
        return { ok: true };
      }
      default:
        return void 0;
    }
  }

  // extension/src/background.js
  var browser = extensionApi();
  var state = createTabState();
  async function getSettings() {
    try {
      const native = await browser.runtime.sendNativeMessage("application.id", { type: "getSettings" });
      if (native?.settings) {
        const settings = normalizeSettings(native.settings);
        await browser.storage.local.set({ settings });
        return settings;
      }
    } catch {
    }
    const stored = await browser.storage.local.get("settings");
    return normalizeSettings(stored.settings || defaultSettings);
  }
  browser.runtime.onMessage.addListener((message, sender, sendResponse) => {
    const result = handleCommand(message, sender, { browser, getSettings, state });
    if (result && typeof result.then === "function") {
      result.then(sendResponse).catch((error) => sendResponse({ ok: false, error: String(error) }));
      return true;
    }
    sendResponse(result);
    return false;
  });
  browser.tabs.onUpdated.addListener((_tabId, _change, tab) => cacheTab(state, tab));
  browser.tabs.onCreated.addListener((tab) => cacheTab(state, tab));
  browser.tabs.onRemoved.addListener((tabId) => rememberClosedTab(state, tabId));
  browser.action?.onClicked?.addListener(async (tab) => {
    await handleToolbarClick(tab, {
      permissions: browser.permissions,
      sendMessage: (tabId, message) => browser.tabs.sendMessage(tabId, message),
      reload: (tabId) => browser.tabs.reload(tabId)
    });
  });
  refreshTabCache(browser, state);
  getSettings();
})();
